### ISSUE TITLE
launch tmux from within python application

### ISSUE THREAD

**Issue by itamargal** [tony/tmuxp#106]
First off, I just found this project, but I already think it's awesome; thank you! Is there a (recommended) way to actually launch tmux programmatically from within a Python application? I don't see it mentioned in the documentation, and I don't see any promising methods in the Server class. Apologies in advance if this is the wrong forum for this sort of question.

**Comment by thomasballinger** [comment]
@itamargal I needed to launch tmux to run some terminal resizing tests in it from Python, here's what I did: https://github.com/thomasballinger/rlundo/blob/master/tmux.py#L145

I'm also curious about a recommended way to do this, but it sounds like you're looking for something like

~~~.py
        self.server = tmuxp.Server()
        try:
            self.session = self.server.sessions[0]
        except tmuxp.exc.TmuxpException:
            self.session = self.server.new_session()
        self.window = self.session.new_window(attach=False)
~~~

**Comment by itamargal** [comment]
@thomasballinger Thanks for the response. I'm trying to run your code, but I'm getting the following error:

    Traceback (most recent call last):
      File "sandbox/tmux2.py", line 198, in <module>
        with TmuxPane(10, 10) as t:
      File "sandbox/tmux2.py", line 176, in __enter__
        self.server.tmux('set', 'automatic-rename', 'on')
    AttributeError: 'Server' object has no attribute 'tmux'

Am I doing something silly?

**Comment by thomasballinger** [comment]
Whoops, I think I'm running an older version of tmuxp. It's not server.tmux anymore, server.cmd, see http://tmuxp.readthedocs.org/en/latest/api.html#tmuxp.Server.cmd

**Comment by itamargal** [comment]
Got it. Thanks!
