### ISSUE TITLE
Use custom tmux executable

### ISSUE THREAD

**Issue by thomasballinger** [tony/tmuxp#115]
Would there be interest in being able to use a custom tmux executable? I need this currently for the Travis tests for https://github.com/thomasballinger/rlundo in order to use their new architecture that doesn't allow installing a custom tmux with sudo, but was planning to monkey-patch it in unless it's something there's other interest in.

**Comment by tony** [comment]
Can you give an example?

I'm open to hear anything and give feedback.

**Comment by tony** [comment]
Oh, I think I understand what you mean now. Like adding an environmental variable / argument to target a tmux binary?

I'm open to that.  I think environmental variable may be appropriate. What do you think of ``TMUXP_TMUX_BIN``?

**Comment by thomasballinger** [comment]
Sounds great! Yes, exactly – making the tmux binary discovery overridable.

Does checking https://github.com/tony/tmuxp/blob/master/tmuxp/util.py#L83 for the environmental variables each time seem appropriate?

**Comment by tony** [comment]
This is a good idea, 

@thomasballinger  I'm teetering between that and ``which()`` https://github.com/tony/tmuxp/blob/master/tmuxp/util.py#L246.

Also, have you tried doing ``PATH=/path/to/my/custom/tmuxdir:$PATH tmuxp <cmd>``?

**Comment by thomasballinger** [comment]
I'm using tmuxp as a Python library, but it seems like this would still work. I don't recall if I tried this or not, but it seems like it would fix it and I can't recall a reason I didn't. I'm all for closing until I actually find out this doesn't work, and I'm not going to get to that for a little while.

**Comment by thomasballinger** [comment]
Maybe it was just seemed messy to change the testing command in the nosetests invocation? This seems like it should be fine though.

**Comment by tony** [comment]
@thomasballinger This is fixed now in www.github.com/tony/libtmux, ``PATH`` is now respected.
