### ISSUE TITLE
Select Tmux options file from Command Line

### ISSUE THREAD

**Issue by fndari** [tony/tmuxp#116]
I'm trying to create a Tmux session from the command line using a test YAML Tmuxp file :

```
tmuxp load myfile.yaml
```

I'm able to set the socket name with the `-L` option:

``` bash
tmuxp -L myserver load myfile.yaml # this works
```

But I'm unable to specify a _Tmux_ configuration file, i.e. corresponding to the `-f` option when starting Tmux from the shell, or to the `source-file` Tmux command:

``` bash
tmuxp -L myserver -f /path/to/my/file.tmux load myfile.yaml # this doesn't work
```

The `config_file` kwarg works as expected when creating the server from the API. I searched through the documentation, and I was unable to find anything decisive, but I have the feeling that I might be missing something obvious. 

Is this functionality supported? I would need the possibility of specifying the config file when creating a session since I have separate `tmux.conf` files for different types of session (`home`, `work`, ...). 

I'm using Tmuxp version 0.9.0, Tmux 1.8.

Thanks in advance, and congratulations on the very nice job

**Comment by tony** [comment]
@fndari Greetings.

It appears tmuxp doesn't pass through the ``-f`` argument to ``tmux(1)``. Do you want to add this functionality? If not, I can investigate it.

**Comment by mcchrish** [comment]
Indeed, having an option to specify tmux configuration file would be useful.

**Comment by condemil** [comment]
As a temporary solution I am calling `shell_command` to load config:

```tmux source-file $XDG_CONFIG_HOME/tmux/tmux.conf```

in one of the panes

**Comment by dkrm0** [comment]
This feature would be pretty good. Is there any chance we could get it?

**Comment by vinnyA3** [comment]
Bumping ^^ .. Is this a thing yet?

**Comment by vinnyA3** [comment]
@tony Ahh yes, also didn't help that I originally installed an older version ... Thanks 👍🏽 .. args work & I now see in the help output
