### ISSUE TITLE
Just installed, "ImportError: cannot import name test_support"

### ISSUE THREAD

**Issue by pumazi** [tony/tmuxp#121]
I just installed tmuxp (``pip install tmuxp``). I received the following error when I run ``tmuxp --help`` or anything tmuxp.

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 7, in <module>
    from tmuxp import cli
  File "/usr/local/lib/python2.7/site-packages/tmuxp/__init__.py", line 17, in <module>
    from .session import Session
  File "/usr/local/lib/python2.7/site-packages/tmuxp/session.py", line 14, in <module>
    from .window import Window
  File "/usr/local/lib/python2.7/site-packages/tmuxp/window.py", line 14, in <module>
    from . import util, formats, exc
  File "/usr/local/lib/python2.7/site-packages/tmuxp/util.py", line 22, in <module>
    from . import exc
  File "/usr/local/lib/python2.7/site-packages/tmuxp/exc.py", line 14, in <module>
    from ._compat import implements_to_string
  File "/usr/local/lib/python2.7/site-packages/tmuxp/_compat.py", line 36, in <module>
    from test import test_support as support
ImportError: cannot import name test_support
```

I'm on OS X 10.10 with (homebrew installed) Python 2.7.9.

**Comment by tony** [comment]
I've never encountered this (I also run tmuxp on a test machine).

What is your pip version? (`pip -V`)?  Also can I see your `which pip` and `which python`?

How did you install your pip?  Did you use `sudo python get-pip.py` from the official pip site?

**Comment by mprat** [comment]
I have the same problem: 

OSX 10.10, Anaconda Python 2.7.10
Installed pip with homebrew (i.e. brew install python) but then am using Anaconda Python instead.
pip version 7.1.2

**Comment by pumazi** [comment]
I also have pip version 7.1.2. I don't recall how it was originally installed.

The problem for me is that I have my user site-packages pointing at a virtualenv (for a project that has imports within plpythonu functions). This is where my system is finding the latest version of pip.

I removed the user site-packages synlink, uninstalled tmuxp and reinstalled it. This seems to have corrected the issue for me.

**Comment by tony** [comment]
I haven't recreated it personally yet, I have found this issue can has arisen elsewhere:

- https://github.com/ContinuumIO/anaconda-issues/issues/168
- https://github.com/gevent/gevent/issues/571

**Comment by tony** [comment]
Anyone interested in making a PR for this? @pumazi @mprat

**Comment by tony** [comment]
@pumazi @mprat:

 tmuxp v0.9.3 is up. Give it a try
