### ISSUE TITLE
Session name with dot inside won't load

### ISSUE THREAD

**Issue by tony** [tony/tmuxp#132]
If a session is already open, loading a session name with a dot in between will detect the session as already running and offer to attach it.

```
❯ tmuxp -v
tmuxp 0.9.3
❯ tmux -V
tmux 2.1
```

**Comment by DXist** [comment]
+1

**Comment by tony** [comment]
originally I thought it was due to ``fnmatch(3)``'s period grabbing, its more of an issue with tmux itself.

Related thread from tmux-users list: https://www.mail-archive.com/tmux-users@lists.sourceforge.net/msg05759.html

tmux treats periods in sessions as invalid:

```
❯ tmux new-session -s moo.moo
bad session name: moo.moo
```

**Comment by DXist** [comment]
It's an interesting point. I guess it's possible to handle troubles with tmux invocations at `libtmux` level and raise more meaningful exception.
