### ISSUE TITLE
Can't give multiple configuration files on command line

### ISSUE THREAD

**Issue by madprog** [tony/tmuxp#133]
Hello,

I am trying to load several configuration files at once:

```
tmuxp load wiki-canada.yaml wiki-grapher.yaml
```

However, tmuxp seems to concatenate them:

> (E) [16:01:33] tmuxp.cli cli.command_load():421 wiki-canada.yaml wiki-grapher.yaml not found.

Is this a bug or a feature?

**Comment by tony** [comment]
Neither, it's a functionality that doesn't exist yet.

Interested making a PR? If not I can swing around to it

**Comment by tony** [comment]
@madprog shipped. 0.10.0 is on pypi

**Comment by madprog** [comment]
Thank you!
