### ISSUE TITLE
Switch to click for completion

### ISSUE THREAD

**Issue by tony** [tony/tmuxp#134]
Refactor cli.py on here and vcspull

https://github.com/mitsuhiko/click / http://click.pocoo.org/6/

Has zsh support now since 6.1 - https://github.com/mitsuhiko/click/pull/286 / https://github.com/mitsuhiko/click/commit/85d1121f2c7a4dc30d61928c6937c499daf1aadd

**Comment by tony** [comment]
#160, #158 

Let's switch to click.

**Comment by fpietka** [comment]
working fine, thanks 👍
