### ISSUE TITLE
Bash completion missing from repo and docs

### ISSUE THREAD

**Issue by dentuzhik** [tony/tmuxp#166]
I can't find the file (tmuxp.bash), and link in the docs also missing.
Any other ways I can setup completion?

**Comment by tony** [comment]
We can add it back. We switched from argparse to click in 1.1.

Which completions did you use?

Do you load your sessions via project directories (.tmuxp.yaml, .tmuxp.json) or via ~/.tmuxp/?

**Comment by tony** [comment]
``eval "$(_TMUXP_COMPLETE=source tmuxp)"``

Does that work?

**Comment by dentuzhik** [comment]
Yep, it works, thanks! Added this to my dotfiles:
```
if [[ -n $(which tmuxp) ]]; then
    eval "$(_TMUXP_COMPLETE=source tmuxp)"
fi
```

**Comment by tony** [comment]
That snippet is nice @dentuzhik , what to make a PR to add it ``cli.rst``?

**Comment by dentuzhik** [comment]
Yep, will do that shortly

**Comment by tony** [comment]
@dentuzhik do you still want to make a PR for this ?

https://github.com/tony/tmuxp/edit/master/doc/cli.rst

**Comment by dentuzhik** [comment]
I can do this, but as far as I can see you've already added a section about the completions :)
https://github.com/tony/tmuxp/blob/master/doc/cli.rst#completion

**Comment by tony** [comment]
@dentuzhik You can wrap the ``if`` statement :)
