### ISSUE TITLE
kill-session gone?

### ISSUE THREAD

**Issue by Ch00k** [tony/tmuxp#174]
The `kill-session` command was quite convenient, but I noticed it was removed in 58c0cc0c2767a435bfe102b9d674b6ea3a3e7898. Is there a reason for removing that? Can I substitute it with any other command?

**Comment by tony** [comment]
Yes, it is gone.

We can add it back if you found it to be useful.

How did you use ``kill-session``?  Was it when within a tmux session?  What made the command more convenient that tmux's ``kill-session``?

**Comment by Ch00k** [comment]
I think I can live with tmux's `kill-session` 😃
