### ISSUE TITLE
ERROR:libtmux.session:list index out of range

### ISSUE THREAD

**Issue by oblitum** [tony/tmuxp#176]
For the following session file (`~/.tmuxp/mail.yaml`):

``` yaml
session_name: mail
windows:
- window_name: foo
  panes:
    - mutt
- window_name: bar
  panes:
    - mutt -F ~/.muttrc.bar
```

I'm getting

```
~ ❯❯❯ tmuxp load mail
[Loading] /home/francisco/.tmuxp/mail.yaml
ERROR:libtmux.session:list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/libtmux/common.py", line 238, in __getattr__
    return self._info[self.formatter_prefix + key]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmuxp", line 9, in <module>
    load_entry_point('tmuxp==1.2.0', 'console_scripts', 'tmuxp')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tmuxp/cli.py", line 484, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/lib/python3.5/site-packages/tmuxp/cli.py", line 260, in load_workspace
    builder.build()
  File "/usr/lib/python3.5/site-packages/tmuxp/workspacebuilder.py", line 144, in build
    assert(self.sconf['session_name'] == session.name)
  File "/usr/lib/python3.5/site-packages/libtmux/common.py", line 241, in __getattr__
    (self.__class__, key))
AttributeError: <class 'libtmux.session.Session'> has no property name
```

I'm on ArchLinux using the AUR package: https://aur.archlinux.org/packages/tmuxp.

**Comment by oblitum** [comment]
By the way. I'm trying to load the session but I'm already inside an existing one.

**Comment by oblitum** [comment]
Regardless, the issue also happens when trying to load the session by name while not being inside a tmux session already.

**Comment by tony** [comment]
how have you been @oblitum 

whats the ``tmux -V``?

**Comment by oblitum** [comment]
@tony hi, I'm ok thanks ;-)

the AUR package I'm using is based on the latest tag, 1.2.0.

**Comment by oblitum** [comment]
Same on 1.2.1.

**Comment by tony** [comment]
What's the ``tmux -V``/tmux version? the ``~/.tmux.conf``/tmux config?

**Comment by oblitum** [comment]
- `tmux -V`: 2.2
- `~/.tmux.conf`: <https://github.com/oblitum/dotfiles/blob/archlinux/.tmux.conf>

**Comment by tony** [comment]
See if removing this allows it to load:

```
# Number windows and panes starting at 1 so that we can jump to
# them easier.
set -g base-index 1
set -g pane-base-index 1
```

Make sure you save and exit tmux fully (`killall tmux` if you have to)

**Comment by oblitum** [comment]
No, still get the same issue.

**Comment by tony** [comment]
What about this one:

```
set -g destroy-unattached on
```

Destroying unattached sessions would break tmuxp, since building workspaces happens via sending commands to a detached session.

**Comment by oblitum** [comment]
Yeah! It's working now. So, since that's the culprit, let's try moving for the best resolution for this. First, why I'm using `destroy-unattached`: personal preference, generally when I close all terminals attached to a tmux session I want the session to simply vanish. When I want to enter another session what I do is, I do `<tmux-prefix>:new-session -s foo`.

I've noticed that if I create a new session that have the same name that a tmuxp session I'm about to load, tmuxp asks whether it should load the configuration in the session of same name that already exists. When I choose YES, it doesn't do anything.

If it load the session configuration then, I could still use this approach of creating a session myself and asking tmuxp to load configuration in it while still having `destroy-unattached on`. But it's doing nothing AFAIK.

Thanks for the help, at last now I know a way for get it working.

**Comment by tony** [comment]
> personal preference, generally when I close all terminals attached to a tmux session I want the session to simply vanish.

That's the first time I heard this usage. Since many use multiplexers specifically so sessions persist when all clients are detached.

Regarding this, libtmux/tmuxp could detecti ``destroy-unattached``, and if its on, switch it off while tmuxp builds the session, then turn it on after its done building.

> I've noticed that if I create a new session that have the same name that a tmuxp session I'm about to load, tmuxp asks whether it should load the configuration in the session of same name that already exists. When I choose YES, it doesn't do anything.

That is intended behavior, if a session name already exists, rather than building the session on top of it, it will offer to attach it. If you're already in a tmux client, it will ``switch-client``.

I haven't had anyone else ask for the ability to have tmuxp load on sessions that already exist (or already taking up the name). Is it possible to have tmuxp offer to build sessions on ones that already exist? Well it could lead to accidents for other users who append windows/panes needlessly. It would be possible to check the current session+windows against the config and offer to build them, but it'd add complexity.

**Comment by oblitum** [comment]
> > personal preference, generally when I close all terminals attached to a tmux session I want the session to simply vanish.

> That's the first time I heard this usage. Since many use multiplexers specifically so sessions persist when all clients are detached.

With `destroy-unattached on`, when all terminal emulators are closed, the session still lives on. If I open a new terminal emulator it can attach to the still living session. What differs is the case I close all panes and windows inside the tmux session, then it just dies, which I have been preferring to happen for a long time.

> Regarding this, libtmux/tmuxp could detecti destroy-unattached, and if its on, switch it off while tmuxp builds the session, then turn it on after its done building.

Well nice! I guess that's a good solution.

> That is intended behavior, if a session name already exists, rather than building the session on top of it, it will offer to attach it. If you're already in a tmux client, it will switch-client.

Ah, OK, I didn't realize it was the intention. I thought the contrary, that the intention was to erase the current state if the user choose yes to "load it over the current one".

Personally, any of these solution would do for me, currently I'm just trying to play with tmuxp the first time so anything will do, if I still can stay with my current configuration (`destroy-unattached on`) it's better.

**Comment by oblitum** [comment]
I've stopped using `destroy-unattached on` but, I guess supporting it or detecting it with a warning somehow should be welcome. So I'm leaving this open.

**Comment by tony** [comment]
@oblitum you changed your avatar, wasn't it a pearl jam one before

open to creating a patch / tests? ``WorkspaceBuilder`` could offer a warning, or it could set ``destroy-unattached`` to ``off`` while it runs.

**Comment by oblitum** [comment]
@tony yeah indeed. I notice you changed yours too, wasn't it yourself in jackets before the heaven trigram?

Humm, sorry but at the moment I'm a bit lazy and busy. Maybe I do a pull at random time in future.

**Comment by andrewschreiber** [comment]
In my case, I needed to remove this from my `~/.tmux.conf`:

set -g default-command "reattach-to-user-namespace -l $SHELL"

**Comment by mdeguzis** [comment]
I am getting this as well

```
$ tmuxp freeze --force -f yaml --yes --quiet
Traceback (most recent call last):
  File "/home/deguzim/.local/bin/tmuxp", line 8, in <module>
    sys.exit(cli.cli())
  File "/home/deguzim/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/deguzim/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/deguzim/.local/lib/python3.7/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/deguzim/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deguzim/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/deguzim/.local/lib/python3.7/site-packages/tmuxp/cli/__init__.py", line 52, in cli
    has_minimum_version()
  File "/home/deguzim/.local/lib/python3.7/site-packages/libtmux/common.py", line 602, in has_minimum_version
    if get_version() < LooseVersion(TMUX_MIN_VERSION):
  File "/home/deguzim/.local/lib/python3.7/site-packages/libtmux/common.py", line 476, in get_version
    version = proc.stdout[0].split("tmux ")[1]
IndexError: list index out of range
```

```
$ tmux -V
tmux.orig 2.8
```

tmux.conf: https://gist.github.com/mdeguzis/34ed503de3d016c155d9e8d2ef23751d
