### ISSUE TITLE
Server() module is not defined

### ISSUE THREAD

**Issue by Lokiiiu** [tony/tmuxp#185]
I import tmuxp library in a python code, where I use the 'Server()'. but when i run that code it shows error:  module object has no attribute Server. then I listed the all tmuxp functions there is no module named Server().

So, is problem is in installation or tmuxp has no Server() function?

**Comment by tony** [comment]
Where did you find the example to use tmuxp like this?

If you want to interact with ``Server`` via python, that functionality now exists in [libtmux](https://github.com/tony/libtmux).

**Comment by Lokiiiu** [comment]
yes I am interacting with python.

but i got again some problems
it doesn't recognize findwhere()

code:
#!/usr/bin/env python

import libtmux

def tmux_init(devices, session_name):
    
    #start server
    server = libtmux.Server()

    #find the session created by the init script
    session = server.findWhere({ "session_name": session_name })

    #rename the first window
    session.list_windows()[0].rename_window('main')
    #session.list_windows()[0].split_window(attach=False)
    
    #create a window containing the main log
    winLog = session.new_window(attach=False, window_name='mainLog')
    winLog.split_window(attach=False)

    for id in devices:
        win = session.new_window(attach=False, window_name=str(id))
        win.split_window(attach=False)
        for p in win.list_panes():
            print p

    return session

error:
session = server.findWhere({ "session_name": session_name })
AttributeError: 'Server' object has no attribute 'findWhere'
