### ISSUE TITLE
Can't open documentation menu on mobile browser

### ISSUE THREAD

**Issue by KibaFox** [tony/tmuxp#188]
When I view the documentation at https://tmuxp.readthedocs.io/en/latest/ on a mobile browser, I cannot open the menu because the "Fork me on GitHub" banner is covering the control.

![screenshot_2016-11-09-08-43-19](https://cloud.githubusercontent.com/assets/16481032/20140704/a44a6af4-a65a-11e6-8db1-372cab57eec8.png)

Although the hamburger menu button is visible, it's actually covered by the invisible part of the "Fork me on GitHub" banner.  I was able to reproduce this in Chrome by narrowing the browser window until the view gets switched.

**Comment by tony** [comment]
Fixed here and across libtmux/vcspull/libvcs

Thanks for catching this

**Comment by KibaFox** [comment]
Perfect! Thank you!
