### ISSUE TITLE
maybe `import` can be more convenient

### ISSUE THREAD

**Issue by maple-leaf** [tony/tmuxp#194]
when `tmuxp` import `yml` file from `tmuxinator`, the output will like this:

```
$tmuxp import tmuxinator ~/.tmuxinator/clojure.yml
Convert to [yaml]: yaml
!!python/unicode 'session_name': clojure
!!python/unicode 'start_directory': ~/tmp/cloure-test
!!python/unicode 'windows':
- !!python/unicode 'layout': main-vertical
  !!python/unicode 'panes':
  - vim
  !!python/unicode 'window_name': editor
---------------------------------------------------------------
Configuration import does its best to convert files.
```

I think `!!python/unicode` is useless, cause when I remove it later, tmuxp can load the converted project configure properly.

And then second step for saving is a little wired:
1, it give the path to current directory instead of `$HOME/.tmuxp` (And I think this folder should be create d automaticlly when not exist at first import action). WHY? because a project tmux config file shouldn't be placed inside a project vc.
2,  you have to type the name of file to save while I have specify the name of file to import, this is really wired. Just save the same name is the way to go.

And there's one more thing, I can't find a cmd to create tmuxp style project, instead I have to create a folder named `tmuxp`, and create a file inside it manually. Maybe I miss something from document?

Last I wanna  say is `tmuxp` is great, some config options is more convenient than `tmuxinator`. Hope the project will be the best. :-)

**Comment by tony** [comment]
Thanks for your feedback. It's very much appreciated.

I don't even know how that's popping up, our test suites aren't indicated it. Placing ``python/unicode`` in the yaml is not expected behavior.

 I'm interested in knowing your OS, `python -V`, `tmuxp -V`, `tmux -V` and `pip show pyyaml`.

**Comment by maple-leaf** [comment]
OS:  OS X Yosemite 10.10.4

python -V: Python 2.7.6

tmuxp -V:  `tmuxp 1.2.2`

tmux -V : `tmux 2.1`

pip show pyyaml

```
pip show pyyaml
Name: PyYAML
Version: 3.12
Summary: YAML parser and emitter for Python
Home-page: http://pyyaml.org/wiki/PyYAML
Author: Kirill Simonov
Author-email: xi@resolvent.net
License: MIT
Location: /Library/Python/2.7/site-packages
Requires:
```

**Comment by tony** [comment]
https://stackoverflow.com/questions/1950306/pyyaml-dumping-without-tags

``safe_dump`` may help, but it may cause issues with unicode.

Interested in making a pull request for this?

**Comment by maple-leaf** [comment]
I just know very little knowledge about python, so I think I can't do the task so far. sorry :(

**Comment by tony** [comment]
I will take this on, then.

[Donations](https://www.git-pull.com/support.html) are always appreciated! They help fund my development on this project.
