### ISSUE TITLE
Version check breaks on tmux dev

### ISSUE THREAD

**Issue by fourjay** [tony/tmuxp#199]
I (possibly foolishly) build tmux from source.
Late updates of tmuxp do a version check ``has_required_tmux_version()`` that throws an exception.
I'm pretty sure this because with the source ``tmux -V`` in my environment returns ``tmux master`` with no version number.
I can work around this by commenting out the call to ``has_required_tmux_version()`` and tmuxp runs without issue.
Is there potentially a way to disable the version check?

**Comment by tony** [comment]
@fourjay I'm open to a fix for that.

**Comment by fourjay** [comment]
I'd think the most robust fix would involve some sort of .tmuxprc file, as it would allow seamless alteration of behavior, but that's clearly a significant enhancement.
Most straightforward fix I can see is just to just catch for the version "master"
I've put in

        version = proc.stdout[0].split('tmux ')[1]
        if version == 'master':
              version = '2.3'

in ``has_required_tmux_version()`` (in ``common.py:413``)
which seems easy and fairly clean 

It's clearly not an accurate polling of version number but's that's inherent in the way tmux handles it's version output. ``master`` isn't really a version number :-)

I suspect anyone who's compiling tmux from source has a relatively recent version (or should be able to fix this) so accurate polling might not be needed.

I can put together a pull request if you'd like. Or, as this is a simple request this snippet might be enough?

**Comment by sloria** [comment]
I just ran into this as well. I installed the latest tmux on OSX using `brew install tmux --HEAD`. Therefore, my tmux version is `'master'`.

```
~ ❯ tmux -V
tmux master
~ ❯ tmuxp load -y play
Traceback (most recent call last):
  File "/Users/sloria/miniconda/bin/tmuxp", line 11, in <module>
    sys.exit(cli.cli())
  File "/Users/sloria/miniconda/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sloria/miniconda/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/sloria/miniconda/lib/python3.5/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/sloria/miniconda/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sloria/miniconda/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/sloria/miniconda/lib/python3.5/site-packages/tmuxp/cli.py", line 315, in cli
    has_required_tmux_version()
  File "/Users/sloria/miniconda/lib/python3.5/site-packages/libtmux/common.py", line 417, in has_required_tmux_version
    if StrictVersion(version) <= StrictVersion("1.7"):
  File "/Users/sloria/miniconda/lib/python3.5/distutils/version.py", line 58, in __le__
    c = self._cmp(other)
  File "/Users/sloria/miniconda/lib/python3.5/distutils/version.py", line 170, in _cmp
    if self.version != other.version:
AttributeError: 'StrictVersion' object has no attribute 'version'
```

If I get some free time soon, I'll send a PR to libtmux.

**Comment by tony** [comment]
Can you do a `tmuxp -V` and try seeing if ``pip install -U tmuxp`` fixes it?

**Comment by sloria** [comment]
That doesn't fix it.

The problem is here: https://github.com/tony/libtmux/blob/2f8a925d1b4a83e21dee9debdaf725dc9984304b/libtmux/common.py#L415-L422

The `version` passed to that function is `'master'`.

**Comment by tony** [comment]
I thought we got rid of the StrictVersion also.


Feel free to give a PR a go. I’ll update the dependency and publish to pypi.

On February 8, 2017 at 1:26:49 PM, Steven Loria (notifications@github.com)
wrote:

That doesn't fix it.

The problem is here:
https://github.com/tony/libtmux/blob/2f8a925d1b4a83e21dee9debdaf725dc9984304b/libtmux/common.py#L415-L422

The version passed to that function is 'master'.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tony/tmuxp/issues/199#issuecomment-278434612>, or mute
the thread
