### ISSUE TITLE
Is it possible to load default config from a different path?

### ISSUE THREAD

**Issue by Ilyes512** [tony/tmuxp#205]
I would like to put my dot configuration into 1 folder (say `~/.mydotfiles`) and so I was wondering if it was possible to save my config into that folder and load it automatically instead of having to use `$ tmuxp load ###`.

I think I could do it from within my `.zshrc`-file and put a line that loads a default config, but I am wondering if there is a better way?

**Comment by tony** [comment]
@Ilyes512 This seems like a good idea for a feature. Perhaps a `TMUXP_CONFIGDIR` or `TMUXP_DIR`.  What do you think?

Interested in making a patch?  You could do it via https://github.com/tony/tmuxp/blob/5b08012d35d902cafc7c4c2ce95fbb6e2a9cd139/tmuxp/cli.py#L28

**Comment by Ilyes512** [comment]
I am not Python dev, but I will give it a shot. First thing I noticed while installing the dev version is that I cant run tests:

```
$ make test
py.test
make: py.test: No such file or directory
make: *** [test] Error 1
```

I am going through http://tmuxp.git-pull.com/en/latest/developing.html.

**Comment by Ilyes512** [comment]
Made a pull request (https://github.com/tony/tmuxp/pull/207). I did not add any tests.

I tested it by running the fallowing 2 commands:

```
$ TMUXP_DIR='~/.foobar' tmuxp load foobar
Error: Could not open file config not found in config dir (yaml/yml/json) /Users/ilyes512/.foobar for name: foobar
```

```
$ TMUXP_CONFIG_DIR='~/.test' tmuxp load foobar
Error: Could not open file config not found in config dir (yaml/yml/json) /Users/ilyes512/.test for name: foobar
```

Both `~/.foobar` and `~/.test` did not exist when I executed the above commands.

**Comment by tony** [comment]
I did this with `TMUX_CONFIGDIR`.

**Comment by Ilyes512** [comment]
Finally switched from tmuxinator to tmuxp. I can confirm that this works. It did not work initially because I used `TMUX_CONFIGFIR` instead of `TMUXP_CONFIGDIR` :).
