### ISSUE TITLE
Will there be a release any time soon?

### ISSUE THREAD

**Issue by Ilyes512** [tony/tmuxp#216]
So as the title mentioned, will there be a new release any time soon. 

I would really like to start using the configurable tmuxp folder (https://github.com/tony/tmuxp/pull/207) :)

**Comment by tony** [comment]
It should be in v1.2.5

https://tmuxp.git-pull.com/en/latest/history.html

Give it a shot and let me know if it works

FYI setup.py hasn't changed because it pulls in the version via tmuxp/__about__.py
