### ISSUE TITLE
Feature: apply window option after command exec (synchronize-panes)

### ISSUE THREAD

**Issue by sebastianst** [tony/tmuxp#234]
In tmuxinator you may add `synchronize: after` to a `window` element to let it set ` synchronize-panes: on` *after* the panes' commands have been executed.
In tmuxp I can enable pane synchronization by setting
```
     options:
      synchronize-panes: on
```
However, this enables synchronization *before* the panes' commands have been executed. So I cannot execute different commands in each synchronized pane.
It would be great to have a `options_after:` configuration element to make such constructions possible.

**Comment by tony** [comment]
Closing after #235
