### ISSUE TITLE
Check user config directory even if extension is specified?

### ISSUE THREAD

**Issue by jcrben** [tony/tmuxp#241]
I have my config directory customized with the environment variable `TMUXP_CONFIGDIR`. I've found that if I load a tmux configuration without using an extension, it works properly. But if I use an extension, it tries to look in the current directory.

From the comment at https://github.com/tony/tmuxp/blob/master/tmuxp/cli.py#L169 it seems that this is by design, but it's kind of a confusing design. I'd rather not have to remember whether I need to include the extension or not...

Also, is this documented? Didn't notice it in https://tmuxp.readthedocs.io/en/latest/quickstart.html#cli for example.

**Comment by tony** [comment]
Initially, I may have implemented it that way to imitate tmuxinator's behavior. 

Are you interested in doing a pull request with a test to verify the behavior?

**Comment by jcrben** [comment]
thanks for asking!

tmux still isn't part of my daily workflow, but I'm circling back around to it and perhaps I could offer some help if it becomes part of my workflow. I use byobu (tmux doesn't let me customize where I put my configs) so messing around with that integration right now (see https://github.com/tony/tmuxp/issues/143)
