### ISSUE TITLE
The synchronized option doesn't get applied at least on tmux master build

### ISSUE THREAD

**Issue by kaushalmodi** [tony/tmuxp#250]
I am using tmux built from master, so it is a bit newer than version 2.4.

I tried `tmuxp load 2-pane-synchronized.yaml` from [this example](https://github.com/tony/tmuxp/blob/master/examples/2-pane-synchronized.yaml). There are no errors, by the panes are not in synchronized state.. so the `synchronize-panes: on` option doesn't seem to have got applied.

**Comment by kaushalmodi** [comment]
If I do `tmux show-window-options` in the tmuxp loaded session, I only see:

> automatic-rename off

But surprisingly this test passes:

```py
    window.set_window_option('synchronize-panes', 'on')
    assert window.show_window_options('synchronize-panes') == 'on'
```

**Comment by tony** [comment]
you're running `tmux show-window-options` in the same window you applied the `options_after` too right?

**Comment by kaushalmodi** [comment]
Yes, of course (the example tmuxp config launches just one window). Actually I found this issue as I practically didn't find the panes in the window to be in synchronized state when I set that option in my tmuxp config. And then that mini example also showed that the synchronized panes did not get enabled. 

To verify that, I did `tmux show-window-options`, and that indeed was the case.

So you cannot see this issue on tmux 2.4+?

**Comment by tony** [comment]
Any updates? I don't use synchronize panes.

Can you try to debug it?

**Comment by kaushalmodi** [comment]
The last time I tried, this issue was still there. I am traveling at the moment. I'll be able to get back to this in 2 weeks.

**Comment by kaushalmodi** [comment]
Sorry, I don't have time or know-how on how to debug and fix this. I'll just close this issue. But that doesn't mean that this bug doesn't exists. Hopefully someone can fix this.
