### ISSUE TITLE
Test suppression history having issues

### ISSUE THREAD

**Issue by tony** [tony/tmuxp#310]
The test we're using for https://github.com/tony/tmuxp/blob/883619ad2b38e8337507510d4005278060345e69/tests/test_workspacebuilder.py#L137 is failing on CI and my local system. It needs to be rewritten to be more resilient. 

https://github.com/tony/tmuxp/pull/146 

Tagging @kmactavish

**Comment by tony** [comment]
@kmactavish This is probably my favorite test we have, but the burden of it has been tricky. Probably partially on my part (I think I refactored it).

Can you try to rewrite it / test it in a way that'd work better with our CI / across platforms?

**Comment by kmactavish** [comment]
@tony flaky tests are the worst :stuck_out_tongue_closed_eyes:, I can try to take a look this weekend.

Do you have any specific CI runs that show the errors?

**Comment by tony** [comment]
I probably spoken to soon re: CI, since all those were broken globally and fixed just a few minutes ago acde0f0. I haven't found a test_suppress_history hiccup on CI yet.

I've only verified it breaking on development with macOS with tmux 2.6 so far.
