### ISSUE TITLE
Add tmuxp.zsh to oh-my-zsh plugins

### ISSUE THREAD

**Issue by maksimr** [tony/tmuxp#38]
I think it will be awesome, have tmuxp completion
in official oh-my-zsh plugins :)

**Comment by safaci2000** [comment]
This isn't mine, but it might be of use:  https://github.com/amontalenti/home/blob/master/.tmuxp/.tmuxp.zsh

**Comment by lfilho** [comment]
Maybe it's a better idea to add to `zsh-completions` project? This way everyone benefits, not only oh-my-zsh... tmuxinator is there already: https://github.com/zsh-users/zsh-completions/blob/master/src/_tmuxinator

Any updated plans on this, @tony ? Thanks!
