### ISSUE TITLE
Avoid ugly entry in `ps ux` when tmuxp starts the server

### ISSUE THREAD

**Issue by ThiefMaster** [tony/tmuxp#74]
When using `tmuxp load` with no tmux server running, the server ends up having a _very_ ugly entry in `ps aux` like this:

```
adrian   26291  0.0  0.0  27672  3152 ?        Ss   00:55   0:00 /usr/bin/tmux new-session -smain -P -F#{session_name}?#{session_windows}?#{session_width}?#{session_height}?#{session_id}?#{session_created}?#{session_created_string}?#{session_attached}?#{session_grouped}?#{session_group} -d
```

It would be nice if tmuxp started a tmux server first, created the new session and then killed  the initial session created by tmux itself. Or maybe the tmux devs could add an option to give the server a nicer process name... that would probably be the better solution.

**Comment by tony** [comment]
@ThiefMaster I came back to this issue and noticed the SF link doesn't work (tmux is now on GH).  Do you know if it's backed up on a mailing list somewhere?
