### ISSUE TITLE
Support for 256 colors

### ISSUE THREAD

**Issue by JBKahn** [tony/tmuxp#83]
I'm not sure how you'd want to implement this in terms or arguments and whatnot. I manually changed ```[which('tmux')]``` to ```[which('tmux'), '-2']``` on line https://github.com/tony/tmuxp/blob/cbf78d442947e7ff801c77d12451a554ad0a2920/tmuxp/util.py#L79 in order to get proper colors in vim.

**Comment by shaief** [comment]
Thanks! That is a good solution. Is there a way to put it in tmuxp configuration?

**Comment by JBKahn** [comment]
Could add a way (if none exists) to add a config option but additional args to pass to tmux?

**Comment by JBKahn** [comment]
For*

**Comment by JBKahn** [comment]
This was already supported......I just missed it in the docs the first time (checked back to the version I was originally on):
http://tmuxp.readthedocs.org/en/latest/cli.html#load-session

My bad.
