### ISSUE TITLE
send_keys sends space

### ISSUE THREAD

**Issue by thomasballinger** [tony/tmuxp#93]
I'm confused as to why `send_keys()` sends a space first. If this is intended behavior, it'd be nice to document it. https://github.com/tony/tmuxp/blob/3887bdc87b89a905c9fb6d59a2a03ced83538bf3/tmuxp/pane.py#L84

I'm happy to take a shot at either documenting or fixing, but wondering which is preferred.

Edit: Whoops, perhaps I'm confused. Looking into this more.

**Comment by tony** [comment]
For the record, the space is added to avoid polluting the user's shell history.  I think that's worth adding to the documentation (either in docs/ or in the code). Are you interested?

**Comment by tony** [comment]
Way to go @thomasballinger !
