### ISSUE TITLE
Already inside TMUX, switch to session? Yes, please!

### ISSUE THREAD

**Issue by oschrenk** [tony/tmuxp#97]
TMUX is running all day, every day and yes please switch to that session. Is there way to configure tmuxp to always answer this question with yes?

**Comment by tony** [comment]
@oschrenk :   Try to add the ``-y`` flag.   Does that work?

**Comment by oschrenk** [comment]
It does. I just didn't know about it. Where is it mentioned in the docs. `man tmuxp` or `tmuxp -h` were not that helpful.

**Comment by tony** [comment]
http://tmuxp.readthedocs.org/en/latest/cli.html#load-session.  It should also be in ``tmuxp load -h``.

That said, starting tmuxp session within another session and the ``-y`` command isn't covered elsewhere in the docs. It seems worth adding to http://tmuxp.readthedocs.org/en/latest/quickstart.html. Are you interested?

**Comment by oschrenk** [comment]
Sure. Give me some time and I'll send a pull request when I'm done.
