### ISSUE TITLE
Custom Layout

### ISSUE THREAD

**Issue by nfarrar** [tony/tmuxp#98]
I've played around with the premade layouts (main-horizontal, main-vertical) ... but I'm confused on how I can do something more complex with a customized layout. Specifically, I'd like to build the following (I'm doing this with shell scripts ATM and it's a PITA):
![Layout Diagram](http://c1.staticflickr.com/9/8823/17174008155_64a6b2752f_b.jpg)

Using the premade layouts (main-vertical & main-horizontal) are pretty straight-forward, but I don't see much documentation on using a custom layout and how to specify the size parameters, etc. Is this possible with tmuxp? Can you point me in the right direction?

**Comment by nfarrar** [comment]
Ah! So looking through the wiki I found the `freeze` command. I manually created my layout, then froze it, then adjusted the source and ended up with:

    session_name: tintin
    start_directory: /Users/nfarrar/Dropbox/Projects/mudfiles
    windows:
    - window_name: tintin
      layout: 73b7,272x67,0,0{60x67,0,0[60x33,0,0,1,60x33,0,34,2],150x67,61,0[150x2,61,0,3,150x64,61,3,4],60x67,212,0[60x33,212,0,5,60x33,212,34,6]}
      focus: 'true'
      panes:
      - clear && tail -f _tmp/map.txt
      - clear && tail -f _tmp/debug.txt
      - clear && tail -f _tmp/sessions.txt
      - shell_command: echo 'main'
        focus: 'true'
      - clear && tail -f _tmp/messages.txt
      - clear && tail -f _tmp/combat.txt
    - window_name: wiki
      panes:
      - echo 'wiki'
    - window_name: src
      panes:
      - echo 'src'

It works, but I don't fully understand what all values in the `layout` represent (the height and width are obvious, but the rest seem undocumented).

**Comment by ThiefMaster** [comment]
It's not meant to be understood (or modified - it's even "protected" with a checksum). The way to use it is to arrange a window in the layout you want and then use `tmux display-message -p "#{window_layout}"` to get the layout string.

**Comment by nfarrar** [comment]
Awesome, thanks for pointing me in the right direction. After looking into tmux's underlying layout feature I get how this works now.
